baseURL = 'https://movequietly.eu/'
languageCode = 'cs'
title = 'Move quietly and plant things'
theme = 'PaperMod'

[params]
  # Vzhled a funkce
  author = { name = "Edgar Walden" }
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  
  # Dark/Light mode
  defaultTheme = "auto" # auto, light, dark
  
  # Sociální ikony
  [[params.socialIcons]]
    
  
  [[params.socialIcons]]
    
# Menu
[[menu.main]]
  name = "Archiv"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "Tagy"
  url = "/tags/"
  weight = 20

[[menu.main]]
  name = "O zahradě"
  url = "/about/"
  weight = 30

