site_name: MOVE QUIETLY AND PLANT THINGS

theme:
  name: material
  language: cs
  features:
    - navigation.indexes
  palette:
    primary: blue grey
    accent: deep orange
  
copyright: Obsah můžete využít podle potřeby. Citace a fotky s uvedením zdroje. Díky  

plugins:
  - blog:
      blog_dir: .