[build]
  publish = "public"
  command = "node build-web.mjs"

[[redirects]]
  from = "/netlify.toml"
  to = "/404"
  status = 404

# Pokud chceš vlastní doménu, přidej:
[[redirects]]
  from = "https://www.movequietly.eu/*"
  to = "https://movequietly.eu/:splat"
  status = 301
  force = true
